name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Action to check out your repository code

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '25.2.1' # Specify the Node.js version

      - name: Install dependencies
        run: npm install # Install project dependencies

      - name: Build React app
        run: npm run build # Run the build script defined in your package.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4 # Action for deploying to GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Use the default GitHub token for authentication
          publish_dir: ./build # Specify the directory containing the built React app (e.g., 'build' or 'dist')
          # cname: your-domain.com # Optional: If you have a custom domain
